; ============================================================
; Module: test/cases/fileio_load-too-large.asm
; Purpose: AC9, AC13 — verify the oversize-refusal path. The
;          fixture (test/fixtures/big.bin — 33792 bytes = 264
;          sectors of 128, generated by test/Makefile) exceeds
;          GAP_BUFFER_MAX (32768). fileio_load reads 256 full
;          sectors filling gap_start up to gap_end; on the
;          257th iteration the pre-read budget check fires
;          (gap_end - gap_start = 0 < 128) and routes to
;          fileio_abort_too_large.
;
;          Post-abort state (per AC9):
;            - BDOS_CLOSE issued (courtesy)
;            - gapbuf_init re-runs: gap_start = BASE, gap_end
;              = BASE + MAX, cursor_offset = 0
;            - buffer_dirty = 0
;            - filename_buffer[0] = 0 (so a later :w refuses)
;            - status_buffer prefix = "file too large"
;
; AC reference: AC9 (oversize refusal), AC13 (headless coverage).
;
; Sentinel codes at 0xCFFE on failure (TH1):
;   0xE0 — gap_start != GAP_BUFFER_BASE
;   0xE1 — gap_end != GAP_BUFFER_BASE + GAP_BUFFER_MAX
;   0xE2 — cursor_offset != 0
;   0xE3 — buffer_dirty != 0
;   0xE4 — filename_buffer[0] != 0
;   0xE5 — status_buffer[0..13] != "file too large" (B = idx)
;   B    — diagnostic context
; ============================================================

;; --- Pre-ORG production headers ---
    INCLUDE "../../inc/equates.inc"
    INCLUDE "../../inc/bios.inc"
    INCLUDE "../../inc/bdos.inc"
    INCLUDE "../../inc/modes.inc"
    INCLUDE "../../inc/vt52.inc"

;; --- ORG 0x0100, sentinel pre-zero, test_start ---
    INCLUDE "../inc/test_prologue.inc"

;; ----- Test body -----

    XOR     A
    LD      (init_teardown_called), A
    LD      (mode_byte), A
    LD      (status_dirty), A
    LD      (buffer_dirty), A
    LD      (filename_buffer), A
    CALL    gapbuf_init

    LD      HL, .filename
    LD      A, 7                            ; "big.bin"
    CALL    fileio_load

    ;; --- Subtest 1: gap_start = GAP_BUFFER_BASE (buffer reset) ---
    LD      HL, (gap_start)
    LD      DE, GAP_BUFFER_BASE
    OR      A
    SBC     HL, DE
    JR      Z, .ok_gap_start
    LD      B, L
    LD      A, 0xE0
    JP      test_fail
.ok_gap_start:

    ;; --- Subtest 2: gap_end = GAP_BUFFER_BASE + GAP_BUFFER_MAX ---
    LD      HL, (gap_end)
    LD      DE, GAP_BUFFER_BASE + GAP_BUFFER_MAX
    OR      A
    SBC     HL, DE
    JR      Z, .ok_gap_end
    LD      B, L
    LD      A, 0xE1
    JP      test_fail
.ok_gap_end:

    ;; --- Subtest 3: cursor_offset = 0 ---
    LD      HL, (cursor_offset)
    LD      A, H
    OR      L
    JR      Z, .ok_cursor
    LD      B, L
    LD      A, 0xE2
    JP      test_fail
.ok_cursor:

    ;; --- Subtest 4: buffer_dirty = 0 ---
    LD      A, (buffer_dirty)
    OR      A
    JR      Z, .ok_dirty
    LD      B, A
    LD      A, 0xE3
    JP      test_fail
.ok_dirty:

    ;; --- Subtest 5: filename_buffer[0] = 0 (display name zeroed) ---
    LD      A, (filename_buffer)
    OR      A
    JR      Z, .ok_filename
    LD      B, A
    LD      A, 0xE4
    JP      test_fail
.ok_filename:

    ;; --- Subtest 6: status_buffer[0..13] = "file too large" ---
    LD      HL, .expected_status
    LD      DE, status_buffer
    LD      B, 14
    LD      C, 0
.cmp_status:
    LD      A, (DE)
    CP      (HL)
    JR      NZ, .fail_status
    INC     HL
    INC     DE
    INC     C
    DJNZ    .cmp_status
    JR      .ok_status
.fail_status:
    LD      B, C
    LD      A, 0xE5
    JP      test_fail
.ok_status:

    JP      test_pass

.filename:
    DEFB    "big.bin"
.expected_status:
    DEFB    "file too large"

;; ----- LOCAL init_teardown stub -----
    INCLUDE "../inc/test_teardown_stub.inc"
;; ----- test_pass / test_fail labels -----
    INCLUDE "../inc/test_epilogue.inc"

;; ----- Production code under test -----
    INCLUDE "../../src/statusln.asm"
    INCLUDE "../../src/gapbuf.asm"
    INCLUDE "../../src/render.asm"
    INCLUDE "../../src/dispatch.asm"
    INCLUDE "../../src/parser.asm"
    INCLUDE "../../src/exline.asm"
    INCLUDE "../../src/fileio.asm"

;; ----- input_loop stub -----
    INCLUDE "../inc/test_input_loop_stub.inc"

;; ----- state.inc LAST -----
    INCLUDE "../../inc/state.inc"
