; ============================================================
; Module: test/cases/init_default-fcb-too-large.asm
; Purpose: Story 2.3 AC5 + AC16 — verify the OVERSIZE-ABORT
;          path through fileio_load_initial. Pre-populates
;          DEFAULT_FCB with the FCB encoding of big.bin
;          (test/fixtures/big.bin — 33-KB fixture generated by
;          test/Makefile, exceeds GAP_BUFFER_MAX = 32768).
;          fileio_load_initial's BDOS_OPEN succeeds (the file
;          exists on B:), fall through to fileio_load_after_open
;          shares the read loop with :e, the pre-read budget
;          check fires after 256 sectors, fileio_abort_too_large
;          clears filename_buffer[0] and emits msg_file_too_large.
;
;          Pre-state:
;            - DEFAULT_FCB[0]      = 0 (default drive → B:)
;            - DEFAULT_FCB[1..8]   = "BIG     "
;            - DEFAULT_FCB[9..11]  = "BIN"
;            - gapbuf_init applied
;
;          Post-state (after fileio_load_initial):
;            - filename_buffer[0] = 0 (CLEARED — same as :e big.bin)
;            - gap_start          = GAP_BUFFER_BASE (buffer reset)
;            - buffer_dirty       = 0
;            - status_buffer[0..13] = "file too large"
;
; AC reference: AC5 (oversize-abort), AC16 (headless coverage).
;
; Sentinel codes at 0xCFFE on failure (TH1):
;   0xE1 — filename_buffer[0] != 0 (CLEAR contract broken)
;   0xE2 — gap_start != GAP_BUFFER_BASE (buffer not reset)
;   0xE4 — buffer_dirty != 0
;   0xE5 — status_buffer != "file too large" (B = index)
;   B    — diagnostic byte where applicable
; ============================================================

;; --- Pre-ORG production headers ---
    INCLUDE "../../inc/equates.inc"
    INCLUDE "../../inc/bios.inc"
    INCLUDE "../../inc/bdos.inc"
    INCLUDE "../../inc/modes.inc"
    INCLUDE "../../inc/vt52.inc"

;; --- ORG 0x0100, sentinel pre-zero, test_start ---
    INCLUDE "../inc/test_prologue.inc"

;; ----- Test body -----

    XOR     A
    LD      (init_teardown_called), A
    LD      (mode_byte), A
    LD      (status_dirty), A
    LD      (buffer_dirty), A
    LD      (filename_buffer), A
    CALL    gapbuf_init

    ;; Pre-populate DEFAULT_FCB: drive=0 (B: default), BIG.BIN.
    LD      A, 0
    LD      (DEFAULT_FCB + 0), A
    LD      HL, .fcb_basename
    LD      DE, DEFAULT_FCB + 1
    LD      BC, 11
    LDIR
    XOR     A
    LD      HL, DEFAULT_FCB + 12
    LD      (HL), A
    LD      DE, DEFAULT_FCB + 13
    LD      BC, 23
    LDIR

    CALL    fileio_load_initial

    ;; --- Subtest 1: filename_buffer[0] = 0 (CLEARED) ---
    LD      A, (filename_buffer)
    OR      A
    JR      Z, .ok_filename
    LD      B, A
    LD      A, 0xE1
    JP      test_fail
.ok_filename:

    ;; --- Subtest 2: gap_start = GAP_BUFFER_BASE (buffer reset) ---
    LD      HL, (gap_start)
    LD      DE, GAP_BUFFER_BASE
    OR      A
    SBC     HL, DE
    LD      A, H
    OR      L
    JR      Z, .ok_gap_start
    LD      B, L
    LD      A, 0xE2
    JP      test_fail
.ok_gap_start:

    ;; --- Subtest 3: buffer_dirty = 0 ---
    LD      A, (buffer_dirty)
    OR      A
    JR      Z, .ok_dirty
    LD      B, A
    LD      A, 0xE4
    JP      test_fail
.ok_dirty:

    ;; --- Subtest 4: status_buffer = "file too large" (14 chars) ---
    LD      HL, .expected_status
    LD      DE, status_buffer
    LD      B, 14
    LD      C, 0
.cmp_status:
    LD      A, (DE)
    CP      (HL)
    JR      NZ, .fail_status
    INC     HL
    INC     DE
    INC     C
    DJNZ    .cmp_status
    JR      .ok_status
.fail_status:
    LD      B, C
    LD      A, 0xE5
    JP      test_fail
.ok_status:

    JP      test_pass

.fcb_basename:
    DEFB    "BIG     "
    DEFB    "BIN"
.expected_status:
    DEFB    "file too large"                ; 14 chars

;; ----- LOCAL init_teardown stub -----
init_teardown:
    LD      A, 1
    LD      (init_teardown_called), A
    RET
init_teardown_called:    DEFB 0

;; ----- test_pass / test_fail labels -----
    INCLUDE "../inc/test_epilogue.inc"

;; ----- Production code under test (AR25 INCLUDE order) -----
    INCLUDE "../../src/statusln.asm"
    INCLUDE "../../src/gapbuf.asm"
    INCLUDE "../../src/render.asm"
    INCLUDE "../../src/dispatch.asm"
    INCLUDE "../../src/parser.asm"
    INCLUDE "../../src/exline.asm"
    INCLUDE "../../src/fileio.asm"

;; ----- input_loop stub -----
    INCLUDE "../inc/test_input_loop_stub.inc"

;; ----- state.inc LAST -----
    INCLUDE "../../inc/state.inc"
