; ============================================================
; Module: test/cases/init_welcome-hidden-too-large.asm
; Purpose: Story 4.3 AC2 — too-large sibling of
;          init_welcome-hidden-with-arg.asm. Drives the
;          fileio_load_initial parse → BDOS_OPEN-success →
;          fileio_load_after_open → .abort_too_large branch
;          (the file-too-large path) and asserts the 0xAA poison
;          on welcome_active survives the entire path including
;          the abort.
;
;          Story 4.2 AC2 names four non-no-arg branches of
;          fileio_load_initial: .new_file, load-success,
;          file-too-large, can't-read-file. The original test
;          covered only .new_file via NOSUCH.FS. This file pins
;          the file-too-large branch via B:BIG.BIN (33792-byte
;          fixture generated by test/Makefile's fixtures/big.bin
;          recipe — exceeds GAP_BUFFER_MAX = 32768 so the load
;          loop's pre-read budget check fires after 256 sectors
;          and fileio_abort_too_large emits msg_file_too_large).
;
;          Pre-state:
;            - Static block zeroed (gapbuf_init runs).
;            - DEFAULT_FCB[0]      = 0    (FR9 default -> B:)
;            - DEFAULT_FCB[1..8]   = "BIG     "
;            - DEFAULT_FCB[9..11]  = "BIN"
;            - welcome_active      = 0xAA (POISON — any writer
;                                          touching the flag during
;                                          the .abort_too_large path
;                                          breaks the test)
;
;          Post-state (after fileio_load_initial):
;            - welcome_active      == 0xAA (.abort_too_large path
;                                           does NOT touch
;                                           welcome_active — poison
;                                           survives)
;            - status_buffer[0..13] == "file too large" (abort
;                                          emitted msg_file_too_large
;                                          — distinguishes the test
;                                          from a path that
;                                          accidentally succeeds OR
;                                          takes a different abort
;                                          branch)
;
; AC reference: Story 4.3 AC2 (file-too-large sibling test).
;
; Sentinel code at 0xCFFE on failure: 0x9C (reused from Story 4.2
;   T2 per the Story 4.3 sentinel-reuse rule).
;   Context byte (B) on failure encodes the subtest:
;     0x01 — welcome_active != 0xAA (.abort_too_large path TOUCHED
;            the flag — a writer wrote 0 OR a different value; the
;            structural invariant 'only .no_arg writes welcome_active'
;            is broken)
;     0x02 — (intentionally unused — .abort_too_large clears
;            filename_buffer[0] so the Story 2.3 AC4 regression-pin
;            subtest 2 used in the canonical .new_file sibling test
;            cannot fire here. The gap is intentional, not an
;            accident of test authoring.)
;     0x03 — status_buffer prefix != "file too large" (abort branch
;            did not emit msg_file_too_large; could be a path that
;            accidentally succeeded OR took a different abort
;            branch — B = byte index of first mismatch)
; ============================================================

;; --- Pre-ORG production headers ---
    INCLUDE "../../inc/equates.inc"
;; BIOS_CONOUT override: the .abort_too_large branch does not emit
;; to BIOS today, but bdos_error_funnel emits via render_emit_byte
;; → BIOS_CONOUT on any sign-bit BDOS error (e.g. BDOS_CLOSE failure
;; inside fileio_abort_too_large). Defensively override so a future
;; BDOS regression cannot corrupt the harness PASS/FAIL grep with
;; terminal escapes. The DEFINE BIOS_CONOUT_OVERRIDE MUST come
;; BEFORE INCLUDE "../../inc/bios.inc".
    DEFINE BIOS_CONOUT_OVERRIDE
BIOS_CONOUT EQU test_bios_conout
    INCLUDE "../../inc/bios.inc"
    INCLUDE "../../inc/bdos.inc"
    INCLUDE "../../inc/modes.inc"
    INCLUDE "../../inc/vt52.inc"

;; --- ORG 0x0100, sentinel pre-zero, test_start ---
    INCLUDE "../inc/test_prologue.inc"

;; ----- Test body -----

    XOR     A
    LD      (init_teardown_called), A
    LD      (mode_byte), A
    LD      (status_dirty), A
    LD      (buffer_dirty), A
    LD      (filename_buffer), A
    LD      (test_capture_len), A         ; clear BIOS capture buffer
    LD      A, 0xAA                       ; poison welcome_active so any
    LD      (welcome_active), A           ; writer (0 OR 1) is detected
    CALL    gapbuf_init

    ;; Pre-populate DEFAULT_FCB with the too-large filename
    ;; BIG.BIN (CCP-format: 8-byte basename space-padded, 3-byte
    ;; ext space-padded). Drive byte 0 -> FR9 default -> B:.
    XOR     A
    LD      (DEFAULT_FCB + 0), A          ; drive byte 0
    LD      A, 'B'
    LD      (DEFAULT_FCB + 1), A
    LD      A, 'I'
    LD      (DEFAULT_FCB + 2), A
    LD      A, 'G'
    LD      (DEFAULT_FCB + 3), A
    LD      A, ' '
    LD      (DEFAULT_FCB + 4), A
    LD      (DEFAULT_FCB + 5), A
    LD      (DEFAULT_FCB + 6), A
    LD      (DEFAULT_FCB + 7), A
    LD      (DEFAULT_FCB + 8), A
    LD      A, 'B'
    LD      (DEFAULT_FCB + 9), A
    LD      A, 'I'
    LD      (DEFAULT_FCB + 10), A
    LD      A, 'N'
    LD      (DEFAULT_FCB + 11), A

    ;; Call fileio_load_initial. Takes parse → BDOS_OPEN-success
    ;; → fileio_load_after_open → .abort_too_large (the pre-read
    ;; budget check fires after 256 sectors on the 33792-byte
    ;; fixture; fileio_abort_too_large emits msg_file_too_large
    ;; and clears filename_buffer[0]).
    CALL    fileio_load_initial

    ;; --- Subtest 1: welcome_active == 0xAA (poison survived — no writer
    ;;     touched the flag on the .abort_too_large path) ---
    LD      A, (welcome_active)
    CP      0xAA
    JR      Z, .ok_active_poison_survived
    LD      B, 0x01
    LD      A, 0x9C
    JP      test_fail
.ok_active_poison_survived:

    ;; --- Subtest 3: status_buffer[0..13] == "file too large" (14 chars) ---
    LD      HL, .expected_status
    LD      DE, status_buffer
    LD      B, 14
    LD      C, 0
.cmp_status:
    LD      A, (DE)
    CP      (HL)
    JR      NZ, .fail_status
    INC     HL
    INC     DE
    INC     C
    DJNZ    .cmp_status
    JR      .ok_status
.fail_status:
    LD      B, C                          ; B = index of first mismatch
    LD      A, 0x9C
    JP      test_fail
.ok_status:

    JP      test_pass

.expected_status:
    DEFB    "file too large"              ; 14 chars

;; ----- LOCAL stubs -----

;; --- BIOS_CONOUT capture buffer ---
    INCLUDE "../inc/test_bios_conout_capture.inc"

;; --- init_teardown stub ---
    INCLUDE "../inc/test_teardown_stub.inc"

;; ----- test_pass / test_fail labels -----
    INCLUDE "../inc/test_epilogue.inc"

;; ----- Production code under test (AR25 INCLUDE order) -----
    INCLUDE "../../src/statusln.asm"
    INCLUDE "../../src/gapbuf.asm"
    INCLUDE "../../src/render.asm"
    INCLUDE "../../src/welcome.asm"
    INCLUDE "../../src/dispatch.asm"
    INCLUDE "../../src/parser.asm"
    INCLUDE "../../src/motions.asm"
    INCLUDE "../../src/edits.asm"
    INCLUDE "../../src/visual.asm"
    INCLUDE "../../src/search.asm"
    INCLUDE "../../src/exline.asm"
    INCLUDE "../../src/fileio.asm"
    INCLUDE "../../src/undo.asm"

;; ----- input_loop stub -----
    INCLUDE "../inc/test_input_loop_stub.inc"

;; ----- state.inc LAST -----
    INCLUDE "../../inc/state.inc"
